title: "[general] "
labels: ["general"]
body:
- type: checkboxes
  attributes:
    label: "Help"
    options:
    - label: "I understand and agree to <https://books.ropensci.org/targets/help.html>."
      required: true
- type: textarea
  attributes:
    label: "Description"
    description: "Please describe your topic and provide a reprex if troubleshooting."
    value: "Please describe your topic and provide a reprex if troubleshooting."
